export type Metrics = {
  poolId: string | null;
  poolHex: string | null;
  liveStake: string | null;
  liveStakeRaw: number | string | null;
  activeStake: string | null;
  activeStakeRaw: number | string | null;
  fixedFee: string | null;
  fixedFeeRaw: number | string | null;
  variableFee: string | null;
  variableFeeRaw: number | string | null;
  pledge: string | null;
  pledgeRaw: number | string | null;
  livePledge: string | null;
  livePledgeRaw: number | string | null;
  saturation: string | null;
  saturationRaw: number | string | null;
  delegators: string | null;
  delegatorsRaw: number | string | null;
  lifetimeBlocks: string | null;
  lifetimeBlocksRaw: number | string | null;
  currentEpochBlocks: string | null;
  currentEpochBlocksRaw: number | string | null;
  lastEpoch: string | null;
  lastEpochRewards: string | null;
  lastEpochRewardsRaw: number | string | null;
  lastEpochFees: string | null;
  lastEpochFeesRaw: number | string | null;
  lastEpochDelegatorRewards: string | null;
  lastEpochDelegatorRewardsRaw: number | string | null;
  effectiveFee: string | null;
  effectiveFeeRaw: number | string | null;
  kesRotations: number | null;
  updatedAt: string | null;
  source: string | null;
};
